version: '2'
services:
  db:
    image: "mysql:5.6"
    container_name: cherrydeck_mysql
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - "3306"
  web:
    build: .
    command: "npm start"
    ports:
      - "5050:1337"
    volumes:
      - ./:/app
    environment:
      - NODE_PATH=/global/node_modules      
    depends_on:
      - "db"
    links:
      - db:mysql
 