version: '2.0'
services:
  db:
    image: "mysql:5.6"
    container_name: cherrydeck_mysql
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - "3306"
    ports:
      - "3306:3306"
  web:
    build: .
    command: "npm start"
    entrypoint: ./docker-entrypoint.sh mysql 3306
    ports:
      - "5050:1337"
    volumes:
      - ./docker-entrypoint.sh:/app/docker-entrypoint.sh
      - ./api:/app/api
      - ./assets:/app/assets
      - ./config:/app/config
      - ./test:/app/test
      - ./.sailsrc:/app/.sailsrc
    depends_on:
      - "db"
    links:
      - db:mysql
 
