module.exports = {
  usernames: [
    'Playboyize',
    'Gigastrength',
    'Deadlyinx',
    'Techpill',
    'Methshot',
    'Methnerd',
    'TreeEater',
    'PackManBrainlure',
    'Carnalpleasure',
    'Sharpcharm',
    'Snarelure',
    'Skullbone',
    'Burnblaze',
    'Emberburn',
    'Emberfire',
    'Evilember',
    'Firespawn',
    'Flameblow',
    'SniperGod',
    'TalkBomber',
    'SniperWish',
    'RavySnake',
    'WebTool',
    'TurtleCat',
    'BlogWobbles',
    'LuckyDusty',
    'RumChicken',
    'StonedTime',
    'CouchChiller',
    'VisualMaster',
    'DeathDog',
    'ZeroReborn',
    'TechHater',
    'eGremlin',
    'BinaryMan',
    'AwesomeTucker',
    'FastChef',
    'JunkTop',
    'PurpleCharger',
    'CodeBuns',
    'BunnyJinx',
    'GoogleCat',
    'StrangeWizard',
    'Fuzzy_Logic',
    'New_Cliche',
    'Ignoramus',
    'Stupidasole',
    'whereismyname',
    'Nojokur',
    'Illusionz',
    'Spazyfool',
    'Supergrass',
    'Dreamworx',
    'Fried_Sushi',
    'Stark_Naked',
    'Need_TLC',
    'Raving_Cute',
    'Nude_Bikergirl',
    'Lunatick',
    'Garbage Can Lid',
    'Crazy_Nice',
    'Booteefool',
    'Harmless_Venom',
    'Lord_Tryzalot',
    'Sir_Gallonhead',
    'Boy_vs_Girl',
    'MPmaster',
    'King_Martha',
    'Spamalot',
    'Soft_member',
    'girlDog',
    'Evil_kitten',
    'farquit',
    'viagrandad',
    'happy_sad',
    'haveahappyday',
    'SomethingNew',
    '5mileys',
    'cum2soon',
    'takes2long',
    'w8t4u',
    'askme',
    'Bidwell',
    'massdebater',
    'iluvmen',
    'Inmate',
    'idontknow',
    'likme',
    'lostmypassword',
    'kizzmybutt',
    'hairygrape',
    'Poker_Star',
    'justo.',
    'fringilla',
    'ipsum.',
    'magna',
    'non,',
    'mus.',
    'nec',
    'dui,',
    'quam',
    'elit.',
    'lacus,',
    'non',
    'libero',
    'sit',
    'molestie',
    'lorem',
    'Nullam',
    'egestas',
    'ac',
    'condimentum.',
    'et',
    'ultricies',
    'odio',
    'libero',
    'ac',
    'magna',
    'gravida.',
    'mauris',
    'volutpat.',
    'elit',
    'tortor,',
    'lobortis.',
    'sodales',
    'Proin',
    'dolor',
    'enim.',
    'per',
    'cursus.',
    'mauris',
    'ac',
    'Duis',
    'quis',
    'enim',
    'ac',
    'Sed',
    'Proin',
    'sit',
    'justo',
    'quis',
    'lacus.',
    'orci',
    'lacinia',
    'blandit',
    'lorem,',
    'vulputate',
    'fames',
    'in',
    'et,',
    'nisl',
    'sagittis',
    'Nulla',
    'eleifend',
    'Phasellus',
    'Nam',
    'Nunc',
    'Fusce',
    'velit.',
    'porttitor',
    'Sed',
    'dui.',
    'Nunc',
    'tortor.',
    'elementum',
    'cursus',
    'dapibus',
    'consequat,',
    'Vivamus',
    'arcu.',
    'diam',
    'Sed',
    'vulputate',
    'enim',
    'turpis',
    'amet',
    'nec',
    'magnis',
    'ut',
    'netus',
    'leo.',
    'lacinia.',
    'dictum',
    'iaculis',
    'sagittis',
    'nunc',
    'quis,',
    'nec',
    'vitae',
    'dui',
    'tempor',
    'nec'
  ],
  fullnames: [
    'Keely Lowery',
    'Christen Jacobs',
    'Wendy Decker',
    'Amelia Lewis',
    'Kessie Alford',
    'Olga Bernard',
    'Cassidy Lowe',
    'Selma Dillon',
    'Zelenia Black',
    'Nelle Wood',
    'Cleo Whitney',
    'Ann Strong',
    'Hayfa Short',
    'Doris Norris',
    'Kaden Hansen',
    'Florence Burks',
    'Riley Kramer',
    'Maya West',
    'Destiny Head',
    'Marah Ford',
    'Constance Roy',
    'Hadley Petty',
    'Catherine Lee',
    'Stacy Smith',
    'Brenna Hood',
    'Ruby Spears',
    'Tanisha Gonzalez',
    'Hedda Head',
    'Maite Cross',
    'Kirby Santiago',
    'Mara Cruz',
    'Blaine Rios',
    'Ursa Holcomb',
    'Ora Clark',
    'Hannah Brewer',
    'Shoshana Greene',
    'Eugenia Campbell',
    'Lillian Lawson',
    'Deirdre Mcpherson',
    'Whitney Vaughan',
    'Tanya Reed',
    'Althea Allison',
    'Olga Thompson',
    'Guinevere Lindsay',
    'Victoria Crawford',
    'Vanna Kim',
    'Leilani Shelton',
    'Pamela Guthrie',
    'Zena Glenn',
    'McKenzie Pena',
    'Stacy Ashley',
    'Pamela Ramos',
    'Shay Callahan',
    'Nora Ballard',
    'Aiko Mccall',
    'Uma Acosta',
    'Marah Valdez',
    'Tallulah Vang',
    'Lavinia Harris',
    'Claire Brewer',
    'Jolie Holcomb',
    'Haley Lang',
    'Kimberley Fry',
    'Hayley Anderson',
    'Mari Sweeney',
    'Regina Espinoza',
    'Hayfa Shannon',
    'Minerva Galloway',
    'Jolene Keith',
    'Audrey Walker',
    'Lenore Diaz',
    'Quinn Knight',
    'Tatum Petersen',
    'Clio Juarez',
    'Martha Warren',
    'Lynn Bright',
    'Tamekah Bowen',
    'Mira Graves',
    'TaShya Harper',
    'Anika Glenn',
    'Mechelle Chavez',
    'TaShya Freeman',
    'Madison Jacobs',
    'Cheryl Joyner',
    'Maryam Evans',
    'Rose Buchanan',
    'Scarlett Carroll',
    'Anne Burke',
    'Lacota Blankenship',
    'Lisandra Barnett',
    'Cailin Kaufman',
    'Lydia Ware',
    'Yolanda Howe',
    'Lillian Mcgowan',
    'Ariana Gamble',
    'Sonya Clemons',
    'Ruby David',
    'Uma Nguyen',
    'Yvette Salazar',
    'Emerald Mitchell',
    'Evan Wheeler',
    'Reuben Stevenson',
    'Ivor Rogers',
    'Jared Leblanc',
    'Stewart Collins',
    'Hyatt Booker',
    'Harding Franklin',
    'Anthony Figueroa',
    'Samson Glover',
    'Zephania Townsend',
    'Hall Clemons',
    'Dieter Mooney',
    'Alden Byrd',
    'Reuben Hammond',
    'Gavin Montoya',
    'Adam Shaffer',
    'Chandler Bauer',
    'Gregory Parrish',
    'Clinton Conway',
    'Dante Davidson',
    'Brandon Downs',
    'Christian Young',
    'Jason Larson',
    'Calvin Craft',
    'Ignatius Shaw',
    'Reed Olson',
    'Hyatt Burns',
    'Vaughan Vaughn',
    'Cade Murphy',
    'Micah Mack',
    'Brody Whitley',
    'Griffith Mcgowan',
    'Stephen Holman',
    'Ray Rosa',
    'Brett Saunders',
    'Evan Becker',
    'Damon French',
    'Scott Willis',
    'Andrew Irwin',
    'Patrick Monroe',
    'Thomas Chen',
    'Josiah Stevens',
    'Alexander Chen',
    'Clinton Keith',
    'Connor Medina',
    'Porter Moss',
    'Palmer Schroeder',
    'Tad Witt',
    'Ignatius Morton',
    'Rogan Sears',
    'George Clay',
    'Gabriel Bailey',
    'Rogan Sharpe',
    'Calvin Rosario',
    'Jerry Mckee',
    'Devin Sims',
    'Paki Newman',
    'Charles Hendrix',
    'Cedric Gilliam',
    'Tanner Stuart',
    'Finn Bush',
    'Tyler Hyde',
    'Reed Blankenship',
    'Thaddeus Palmer',
    'Amos Jenkins',
    'Hyatt Pope',
    'Jason Dennis',
    'Gregory Kemp',
    'Omar Atkins',
    'Brett Colon',
    'Channing Rodriguez',
    'Galvin Lloyd',
    'Dustin Delaney',
    'Emmanuel Dorsey',
    'Caesar Manning',
    'Gavin Tanner',
    'Francis Whitaker',
    'Zephania Snyder',
    'Raphael Deleon',
    'Lamar Rodriguez',
    'Kamal Jimenez',
    'Julian Shaffer',
    'Holmes House',
    'Hayes Hodge',
    'Kieran Bean',
    'Jerome Curry',
    'Kasimir Chase',
    'Fletcher Walsh',
    'Garrison Justice',
    'Steel Mueller',
    'Kennan Bray',
    'Elmo Vaughan',
    'Brendan Rice',
    'Colin Holden',
    'Hiram Mitchell',
    'Quentin Stephens',
    'Rooney Stephens',
    'Zephania Burton',
    'Gareth Leblanc',
    'Victor Trevino'
  ],
  avatars: [
    'https://randomuser.me/api/portraits/men/1.jpg',
    'https://randomuser.me/api/portraits/men/2.jpg',
    'https://randomuser.me/api/portraits/men/3.jpg',
    'https://randomuser.me/api/portraits/men/4.jpg',
    'https://randomuser.me/api/portraits/men/5.jpg',
    'https://randomuser.me/api/portraits/men/6.jpg',
    'https://randomuser.me/api/portraits/men/7.jpg',
    'https://randomuser.me/api/portraits/men/8.jpg',
    'https://randomuser.me/api/portraits/men/9.jpg',
    'https://randomuser.me/api/portraits/men/10.jpg',
    'https://randomuser.me/api/portraits/men/11.jpg',
    'https://randomuser.me/api/portraits/men/12.jpg',
    'https://randomuser.me/api/portraits/men/13.jpg',
    'https://randomuser.me/api/portraits/men/14.jpg',
    'https://randomuser.me/api/portraits/men/15.jpg',
    'https://randomuser.me/api/portraits/men/16.jpg',
    'https://randomuser.me/api/portraits/men/17.jpg',
    'https://randomuser.me/api/portraits/men/18.jpg',
    'https://randomuser.me/api/portraits/men/19.jpg',
    'https://randomuser.me/api/portraits/men/20.jpg',
    'https://randomuser.me/api/portraits/men/21.jpg',
    'https://randomuser.me/api/portraits/men/22.jpg',
    'https://randomuser.me/api/portraits/men/23.jpg',
    'https://randomuser.me/api/portraits/men/24.jpg',
    'https://randomuser.me/api/portraits/men/25.jpg'
  ],
  locations: [
    { lat: 46.7213419, lon: 16.0136084 },
    { lat: 48.8587741, lon: 2.2069771 },
    { lat: 40.6976637, lon: -74.1197633 }
  ],

  generateUser: () => {
    const randomPoint = arrayHelpers.getRandomArrayItem(
      seederHelpers.locations
    );
    return {
      username: arrayHelpers.getRandomArrayItem(seederHelpers.usernames),
      firstName: arrayHelpers
        .getRandomArrayItem(seederHelpers.fullnames)
        .split(' ')[0],
      lastName: arrayHelpers
        .getRandomArrayItem(seederHelpers.fullnames)
        .split(' ')[1],
      avatar: arrayHelpers.getRandomArrayItem(seederHelpers.avatars),
      lat: randomPoint.lat,
      lon: randomPoint.lon,
      status: 'ACTIVE'
    };
  },

  generatePhotographer: userId => {
    return {
      userId,
      studio: Math.random() >= 0.5,
      expertise: Math.random() >= 0.5 ? 'professional' : 'amateur',
      priceRange: Math.floor(Math.random() * 5 + 1),
      instagramId: Math.floor(Math.random() * 20000 + 99),
      followers: Math.floor(Math.random() * 2500 + 1000)
    };
  },

  generateCategory: name => {
    return {
      name
    };
  },

  generatePhoto: (photographer, categoryId) => {
    return {
      categoryId,
      photographerId: photographer.id,
      instagramImageId: Math.floor(Math.random() * 300000 + 100000)
    };
  }
};
